/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import util.DbCon;

/**
 *
 * @author imran
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    
    private Sixoptions sixoptions;
    public Dashboard(Sixoptions sixoptions) {
        setUndecorated(true);
        initComponents();
        showTotalStudentCount();
        showTotalTeacherCount();
        showTotalStaffCount();
        showAll();
        this.sixoptions=sixoptions;
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnAdmissionHome = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jTabbedPane5 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        totalStudent = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        showClassOne = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        showClassThree = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        showClassTwo = new javax.swing.JLabel();
        showClassFour = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        showClassFive = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        showClassSix = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        showClassSeven = new javax.swing.JLabel();
        showClassEight = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        showClassNine = new javax.swing.JLabel();
        showClassTen = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        showClassElevne = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        showClassTwelve = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        totalTeacher = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel22 = new javax.swing.JPanel();
        totalStaff = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 102, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAdmissionHome.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAdmissionHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/home.png"))); // NOI18N
        btnAdmissionHome.setText("Home");
        btnAdmissionHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdmissionHomeActionPerformed(evt);
            }
        });
        jPanel2.add(btnAdmissionHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 20, 120, 40));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Dashboard");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 90));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 90));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel19.setBackground(new java.awt.Color(204, 204, 204));
        jPanel19.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel20.setBackground(new java.awt.Color(255, 255, 255));
        jPanel20.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        totalStudent.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        totalStudent.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel20.add(totalStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 90, 40));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Total Student");
        jPanel20.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 140, 50));

        jPanel19.add(jPanel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 240, 150));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Class one");
        jPanel6.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, -1, -1));

        showClassOne.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        showClassOne.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel6.add(showClassOne, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 50, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("Class Three");
        jPanel6.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, -1, -1));

        showClassThree.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        showClassThree.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel6.add(showClassThree, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, 50, 30));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setText("Class Two");
        jPanel6.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, -1, -1));

        showClassTwo.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        showClassTwo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel6.add(showClassTwo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 50, 30));

        showClassFour.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        showClassFour.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel6.add(showClassFour, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, 50, 30));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setText("Class Four");
        jPanel6.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, -1, -1));

        showClassFive.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        showClassFive.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel6.add(showClassFive, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 340, 50, 30));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel16.setText("Class Five");
        jPanel6.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, -1, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel17.setText("Class Six");
        jPanel6.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 410, -1, -1));

        showClassSix.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        showClassSix.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel6.add(showClassSix, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 410, 50, 30));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel19.setText("Class Seven");
        jPanel6.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, -1, -1));

        showClassSeven.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        showClassSeven.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel6.add(showClassSeven, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 110, 50, 30));

        showClassEight.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        showClassEight.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel6.add(showClassEight, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 170, 50, 30));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel22.setText("Class Eight");
        jPanel6.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 170, -1, -1));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel23.setText("Class Nine");
        jPanel6.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 240, -1, -1));

        showClassNine.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        showClassNine.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel6.add(showClassNine, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 240, 50, 30));

        showClassTen.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        showClassTen.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel6.add(showClassTen, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 300, 50, 30));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel26.setText("Class Ten");
        jPanel6.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 300, -1, -1));

        showClassElevne.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        showClassElevne.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel6.add(showClassElevne, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 360, 50, 30));

        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel28.setText("Class Eleven");
        jPanel6.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 360, -1, -1));

        showClassTwelve.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        showClassTwelve.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel6.add(showClassTwelve, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 420, 50, 30));

        jLabel30.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel30.setText("Class Twelve");
        jPanel6.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 420, -1, -1));

        jLabel31.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel31.setText("Total Student By Class");
        jPanel6.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 250, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/background9898.jpg"))); // NOI18N
        jPanel6.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 550));

        jPanel19.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 670, 550));

        jPanel21.setBackground(new java.awt.Color(255, 255, 255));
        jPanel21.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        totalTeacher.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        totalTeacher.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel21.add(totalTeacher, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 90, 40));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Total Teacher");
        jPanel21.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 140, 50));

        jPanel19.add(jPanel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 240, 150));

        jPanel22.setBackground(new java.awt.Color(255, 255, 255));
        jPanel22.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        totalStaff.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        totalStaff.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(totalStaff, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 100, 40));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Total Staff");
        jPanel22.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 120, 50));

        jPanel19.add(jPanel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 240, 150));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane5.addTab("tab1", jPanel4);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1020, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 559, Short.MAX_VALUE)
        );

        jTabbedPane5.addTab("tab2", jPanel5);

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1020, Short.MAX_VALUE)
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 559, Short.MAX_VALUE)
        );

        jTabbedPane5.addTab("tab3", jPanel18);

        jPanel3.add(jTabbedPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 1020, 590));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 1020, 560));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdmissionHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdmissionHomeActionPerformed
        // TODO add your handling code here:
        this.dispose();
        sixoptions.setVisible(true);
        
    }//GEN-LAST:event_btnAdmissionHomeActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public void showTotalStudentCount(){
         int totalStudentCount = 0; // Initialize total count to 0

    String query = "SELECT COUNT(*) AS roll FROM studentdata"; // Get the total count of students
    DbCon dbCon = new DbCon();

    try (Connection connection = dbCon.getCon(); PreparedStatement ps = connection.prepareStatement(query);
         ResultSet rs = ps.executeQuery()) {

        if (rs.next()) {
            totalStudentCount = rs.getInt("roll"); // Get the total student count
        }

        // Set the total student count to a label or display it as needed
        totalStudent.setText("     " + totalStudentCount);

    } catch (SQLException ex) {
        Logger.getLogger(NewAdmissionTest.class.getName()).log(Level.SEVERE, null, ex);
    }
    }
    
    
    
    
    
    
    public void showTotalTeacherCount(){
        int totalTeacherCount = 0; // Initialize total count to 0

    String query = "SELECT COUNT(*) AS teacherId FROM teacherdata"; // Get the total count of students
    DbCon dbCon = new DbCon();

    try (Connection connection = dbCon.getCon(); PreparedStatement ps = connection.prepareStatement(query);
         ResultSet rs = ps.executeQuery()) {

        if (rs.next()) {
            totalTeacherCount = rs.getInt("teacherId"); // Get the total student count
        }

        // Set the total student count to a label or display it as needed
        totalTeacher.setText("     " + totalTeacherCount);

    } catch (SQLException ex) {
        Logger.getLogger(NewAdmissionTest.class.getName()).log(Level.SEVERE, null, ex);
    }
    }
    
    
    
    
    public void showTotalStaffCount(){
        int totalStaffCount = 0; // Initialize total count to 0

    String query = "SELECT COUNT(*) AS staffId FROM staffdata"; // Get the total count of students
    DbCon dbCon = new DbCon();

    try (Connection connection = dbCon.getCon(); PreparedStatement ps = connection.prepareStatement(query);
         ResultSet rs = ps.executeQuery()) {

        if (rs.next()) {
            totalStaffCount = rs.getInt("staffId"); // Get the total student count
        }

        // Set the total student count to a label or display it as needed
        totalStaff.setText("     " + totalStaffCount);

    } catch (SQLException ex) {
        Logger.getLogger(NewAdmissionTest.class.getName()).log(Level.SEVERE, null, ex);
    }
    
    }
    
    
    
    
    
    
    
    public void showAll(){
        int[] classCounts = new int[12];

    String query = "SELECT stdClass, COUNT(*) AS roll FROM studentdata GROUP BY stdClass";
    DbCon dbCon = new DbCon();

    try (Connection connection = dbCon.getCon(); PreparedStatement ps = connection.prepareStatement(query);
         ResultSet rs = ps.executeQuery()) {

        while (rs.next()) {
            int classNumber = rs.getInt("stdClass");
            int count = rs.getInt("roll");
            classCounts[classNumber - 1] = count; // Subtract 1 to use as array index
        }

        // Set the counts to labels
        showClassOne.setText("" + classCounts[0]);
        showClassTwo.setText("" + classCounts[1]);
        showClassThree.setText("" + classCounts[2]);
        showClassFour.setText("" + classCounts[3]);
        showClassFive.setText("" + classCounts[4]);
        showClassSix.setText("" + classCounts[5]);
        showClassSeven.setText("" + classCounts[6]);
        showClassEight.setText("" + classCounts[7]);
        showClassNine.setText("" + classCounts[8]);
        showClassTen.setText("" + classCounts[9]);
        showClassElevne.setText("" + classCounts[10]);
        showClassTwelve.setText("" + classCounts[11]);
        // Similarly, set counts for other classes

    } catch (SQLException ex) {
        Logger.getLogger(NewAdmissionTest.class.getName()).log(Level.SEVERE, null, ex);
    }
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Sixoptions sixoptions=new Sixoptions();
                Dashboard dashboard=new Dashboard(sixoptions);
                dashboard.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdmissionHome;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTabbedPane jTabbedPane5;
    private javax.swing.JLabel showClassEight;
    private javax.swing.JLabel showClassElevne;
    private javax.swing.JLabel showClassFive;
    private javax.swing.JLabel showClassFour;
    private javax.swing.JLabel showClassNine;
    private javax.swing.JLabel showClassOne;
    private javax.swing.JLabel showClassSeven;
    private javax.swing.JLabel showClassSix;
    private javax.swing.JLabel showClassTen;
    private javax.swing.JLabel showClassThree;
    private javax.swing.JLabel showClassTwelve;
    private javax.swing.JLabel showClassTwo;
    private javax.swing.JLabel totalStaff;
    private javax.swing.JLabel totalStudent;
    private javax.swing.JLabel totalTeacher;
    // End of variables declaration//GEN-END:variables
}
