/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.StudentData;
import util.DbCon;

/**
 *
 * @author imran
 */
public class DownloadPayment extends javax.swing.JFrame {

    /**
     * Creates new form DownloadPayment
     */
    
    private int roll;
     private int stdClass;
 
     String query;
  public DownloadPayment(int roll,int stdClass) {
      setUndecorated(true);
     this.roll = roll;
        this.stdClass = stdClass;
    initComponents();
     
    StudentData studentData = getStudentData(roll, stdClass);

        if (studentData != null) {
            // Update UI components with the retrieved student data
            txtId.setText(""+studentData.getRoll());
            txtClass.setText(""+studentData.getStdClass());
            txtName.setText(studentData.getName());
            txtPaymentNumber.setText(studentData.getAccountNumber());
            txtPaymentDate.setText(studentData.getPaymentDate().toString());
            txtAmount.setText(Double.toString(studentData.getAmount()));
            txtAddress.setText(studentData.getAddress());
            txtPaymentOption.setText(studentData.getPaymentMethod());
            // Update other UI components with the corresponding data
        } else {
            // Handle the case where no matching data is found in the database
            // You can show a message or take appropriate action
        }
        
        this.setLocationRelativeTo(null);
   
}
  
  
  

    private DownloadPayment() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

   
  
  private StudentData getStudentData(int roll, int stdClass) {
        DbCon dbCon = new DbCon();
        Connection con = dbCon.getCon();
        StudentData studentData = null;
        try {
            String query = "SELECT * FROM studentdata WHERE roll = ? AND stdClass = ?";
            PreparedStatement preparedStatement = con.prepareStatement(query);
            preparedStatement.setInt(1, roll);
            preparedStatement.setInt(2, stdClass);
            ResultSet resultSet = preparedStatement.executeQuery();

            if (resultSet.next()) {
                studentData = new StudentData();
                // Populate the StudentData object with data from the database
                studentData.setRoll(resultSet.getInt("roll"));
                studentData.setStdClass(resultSet.getInt("stdClass"));
                studentData.setName(resultSet.getString("name"));
                studentData.setAccountNumber(resultSet.getString("accountNumber"));
                studentData.setAmount(resultSet.getDouble("amount"));
                studentData.setPaymentMethod(resultSet.getString("paymentMethod"));
                studentData.setAddress(resultSet.getString("address"));
                
                studentData.setPaymentDate(resultSet.getDate("paymentDate"));
                
                // Set other fields similarly
            }
            con.close();
        } catch (SQLException ex) {
            Logger.getLogger(DownloadPayment.class.getName()).log(Level.SEVERE, null, ex);
        }
        return studentData;
    }

    // Main method for testing

    // Rest of the DownloadPayment class.


  
    
   



   

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelReceipt = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtPaymentDate = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtPaymentNumber = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtPaymentOption = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtName = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtId = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtClass = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtAmount = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnCancel = new javax.swing.JButton();
        btnDownload = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelReceipt.setBackground(new java.awt.Color(255, 255, 255));
        panelReceipt.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel2.setText("Massachusetts Institute of Technology");
        panelReceipt.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 280, 20));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel3.setText("Goverment of Bangladesh");
        panelReceipt.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 170, -1));

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel4.setText("Payment Receipt");
        panelReceipt.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, 160, 40));

        txtPaymentDate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelReceipt.add(txtPaymentDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 240, 150, 20));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Payment date:");
        panelReceipt.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 140, 20));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Payment By:");
        panelReceipt.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 90, 20));

        txtPaymentNumber.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelReceipt.add(txtPaymentNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, 150, 20));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Payment Receipt Number:");
        panelReceipt.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 180, 20));

        txtPaymentOption.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelReceipt.add(txtPaymentOption, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 400, 430, 20));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Name:");
        panelReceipt.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 90, 20));

        txtName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelReceipt.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, 430, 20));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setText("Address");
        panelReceipt.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 90, 20));

        txtAddress.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelReceipt.add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, 430, 20));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel5.setText("Authority Signature");
        panelReceipt.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 460, 150, 20));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slip/qrcode.png"))); // NOI18N
        panelReceipt.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 150, 150));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel19.setText("Roll:");
        panelReceipt.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, 40, 20));

        txtId.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        txtId.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelReceipt.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 100, 60, 20));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slip/signature-2.png"))); // NOI18N
        panelReceipt.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 490, 190, 49));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slip/mit (1).png"))); // NOI18N
        panelReceipt.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 105, 105));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel20.setText("Class:");
        panelReceipt.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 130, 40, 20));

        txtClass.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        txtClass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelReceipt.add(txtClass, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 130, 60, 20));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Amount:");
        panelReceipt.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, 140, 20));

        txtAmount.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelReceipt.add(txtAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 270, 150, 20));

        jPanel1.add(panelReceipt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 670, 600));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCancel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slip/contract.png"))); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        jPanel2.add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, 120, 40));

        btnDownload.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDownload.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slip/printer.png"))); // NOI18N
        btnDownload.setText("Print");
        btnDownload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDownloadActionPerformed(evt);
            }
        });
        jPanel2.add(btnDownload, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 110, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 610, 670, 70));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 690));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDownloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDownloadActionPerformed
        // TODO add your handling code here:
        
 
            PrinterJob job=PrinterJob.getPrinterJob();
        job.setJobName("print Data");
       
        job.setPrintable(new Printable() {
        public int print(Graphics pg, PageFormat pf, int pageNum){
        pf.setOrientation(PageFormat.LANDSCAPE);
        if(pageNum>0){
        return Printable.NO_SUCH_PAGE;
        }
        Graphics2D g2=(Graphics2D)pg;
        g2.translate(pf.getImageableX(),pf.getImageableY());
        g2.scale(0.47, 0.47);
        panelReceipt.print(g2);
        return Printable.PAGE_EXISTS;
        }
       
        });
       
        boolean ok=job.printDialog();
        if(ok){
           
        try{                      
        job.print();        
        }
        catch(PrinterException ex){
        ex.printStackTrace();
        }
        }
    
    }//GEN-LAST:event_btnDownloadActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DownloadPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DownloadPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DownloadPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DownloadPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               new DownloadPayment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDownload;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel panelReceipt;
    private javax.swing.JLabel txtAddress;
    private javax.swing.JLabel txtAmount;
    private javax.swing.JLabel txtClass;
    private javax.swing.JLabel txtId;
    private javax.swing.JLabel txtName;
    private javax.swing.JLabel txtPaymentDate;
    private javax.swing.JLabel txtPaymentNumber;
    private javax.swing.JLabel txtPaymentOption;
    // End of variables declaration//GEN-END:variables
}
