/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.Image;
import java.io.File;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import model.StudentData;
import util.DbCon;

/**
 *
 * @author imran
 */
public class NewAdmissionTest extends javax.swing.JFrame {

    /**
     * Creates new form NewAdmissionTest
     */
    private Sixoptions sixoptions;
    
    public NewAdmissionTest(Sixoptions sixoptions) {
        setUndecorated(true);
        initComponents();
        setLocationRelativeTo(null);
        this.sixoptions=sixoptions;
        //initializeMaxRollByClass();
    }
    
    public  StudentData studentData=new StudentData();
    
    //for sql date
    
    public Date DateToSqlDate(java.util.Date utilDate){
        if(utilDate !=null){
            return new Date(utilDate.getTime());
        }
        return null;
    }
    
    
    public void resetNewAdmission(){
        txtRoll.setText(null);
        //txtComboClass.setSelectedIndex(0);
        txtName.setText("");
        txtLastName.setText("");
        txtFatherName.setText(null);
        txtMothersName.setText("");
        txtAddress.setText("");
        genderMale.setSelected(false);
        genderFemale.setSelected(false);
        txtDate.setDate(null);
        txtAge.setText("");
        choosePicture.setIcon(null);
        
        
                
    }
    
    
    
    
    
//    private void initializeMaxRollByClass(){
//        
//        
//        try {
//             DbCon dbCon = new DbCon();
//        Connection con = dbCon.getCon();
//        Statement stmt = con.createStatement();
//        String query = "select stdClass, MAX(roll) from studentdata group by stdClass";
//        ResultSet result = stmt.executeQuery(query);
//
//        while (result.next()) {
//            int classNumber = result.getInt("stdClass");
//            int maxRoll = result.getInt("MAX(roll)");
//            maxRollByClass.put(classNumber, maxRoll);
//                 
//                 System.out.println("Class "+classNumber+"maxRoll "+maxRoll);
//             }
//             con.close();
//        } catch (SQLException ex) {
//            Logger.getLogger(NewAdmissionTest.class.getName()).log(Level.SEVERE, null, ex);
//        }
//        
//       
//        
//    }
//    
    
//         private Map<Integer,Integer> maxRollByClass=new HashMap<>();
//     
//     
//     private void generateRollNumber(){
//         try {
//             int selectedClass=Integer.parseInt(txtComboClass.getSelectedItem().toString());
//             Integer currentMaxRoll=maxRollByClass.get(selectedClass);
//             
//             if(currentMaxRoll !=null){
//                 int roll=currentMaxRoll.intValue();
//                 txtRoll.setText(Integer.toString(roll));
//                 maxRollByClass.put(selectedClass, roll+1);
//             }
//             else{
//                 txtRoll.setText("1");
//                 maxRollByClass.put(selectedClass, 1);
//             }
//             
//             
//         } catch (NumberFormatException e) {
//             e.printStackTrace();
//         }
//     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnAdmissionHome = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtComboClass = new javax.swing.JComboBox<>();
        choosePicture = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        txtLastName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtFatherName = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtMothersName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAddress = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        genderMale = new javax.swing.JRadioButton();
        genderFemale = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        txtDate = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        btnMakePayment = new javax.swing.JButton();
        txtRoll = new javax.swing.JTextField();
        btnReset = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAdmissionHome.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAdmissionHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/home.png"))); // NOI18N
        btnAdmissionHome.setText("Home");
        btnAdmissionHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdmissionHomeActionPerformed(evt);
            }
        });
        jPanel2.add(btnAdmissionHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 20, 120, 40));

        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel2.setText("Roll");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, 30));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel1.setText("Class:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 70, 20));

        txtComboClass.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtComboClass.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<--Select-->", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", " " }));
        txtComboClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtComboClassActionPerformed(evt);
            }
        });
        jPanel1.add(txtComboClass, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, -1, 30));

        choosePicture.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        jPanel1.add(choosePicture, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 40, 110, 120));

        jButton2.setBackground(new java.awt.Color(204, 255, 204));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jButton2.setText("Choose");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 190, -1, 30));

        txtLastName.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLastNameActionPerformed(evt);
            }
        });
        jPanel1.add(txtLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 140, 140, 30));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel3.setText("Last Name:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, 90, -1));

        txtName.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        jPanel1.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 140, 30));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel10.setText("Name :");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 60, -1));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel11.setText("Fathers Name:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 120, -1));

        txtFatherName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFatherNameActionPerformed(evt);
            }
        });
        jPanel1.add(txtFatherName, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 150, 30));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel9.setText("Mothers Name:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, 120, -1));

        txtMothersName.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtMothersName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMothersNameActionPerformed(evt);
            }
        });
        jPanel1.add(txtMothersName, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, 140, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel7.setText("Address :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, -1));

        txtAddress.setColumns(20);
        txtAddress.setRows(5);
        jScrollPane1.setViewportView(txtAddress);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 190, 50));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel4.setText("Gender :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, -1, 20));

        genderMale.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        genderMale.setText("Male");
        jPanel1.add(genderMale, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, -1, -1));

        genderFemale.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        genderFemale.setText("Female");
        genderFemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderFemaleActionPerformed(evt);
            }
        });
        jPanel1.add(genderFemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 350, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel5.setText("Date of Birth:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, 120, -1));
        jPanel1.add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 402, 210, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel6.setText("Age :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, 60, -1));
        jPanel1.add(txtAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 470, 150, 30));

        btnMakePayment.setBackground(new java.awt.Color(204, 255, 204));
        btnMakePayment.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnMakePayment.setText("Make Payment");
        btnMakePayment.setAutoscrolls(true);
        btnMakePayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMakePaymentActionPerformed(evt);
            }
        });
        jPanel1.add(btnMakePayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 560, 160, 40));

        txtRoll.setEditable(false);
        txtRoll.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txtRoll.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(txtRoll, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 110, 30));

        btnReset.setBackground(new java.awt.Color(255, 153, 153));
        btnReset.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        jPanel1.add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 560, 100, 40));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 760, 660));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 60, 1130, 770));

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setBackground(new java.awt.Color(51, 153, 0));
        jLabel8.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Addmission Form");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1130, 60));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1130, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         



           JFileChooser fileChooser=new JFileChooser();
           FileNameExtensionFilter fnef=new FileNameExtensionFilter("IMAGES", "png", "jpg", "jpeg");
           fileChooser.addChoosableFileFilter(fnef);
           
           int showOpenDialogue=fileChooser.showOpenDialog(null);
           
           if(showOpenDialogue ==JFileChooser.APPROVE_OPTION){
               File selectedImageFile=fileChooser.getSelectedFile();
               String selectedImagePath=selectedImageFile.getAbsolutePath();
               JOptionPane.showMessageDialog(null, selectedImagePath);
               
               //Display the selected image on a jLabel
               
               ImageIcon imageIcon=new ImageIcon(selectedImagePath);
               Image image=imageIcon.getImage().getScaledInstance(choosePicture.getWidth(), choosePicture.getHeight(), Image.SCALE_SMOOTH);
               choosePicture.setIcon(new ImageIcon(image));
               
               studentData.setPicturePath(selectedImagePath);


        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnMakePaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMakePaymentActionPerformed
        // TODO add your handling code here:
        
         
        
        String gender="";
        if(genderMale.isSelected()){
            gender="Male";
        }
        else if(genderFemale.isSelected()){
            gender="Female";
        }
        
        //for date

        
        studentData.setRoll(Integer.parseInt(txtRoll.getText()));   //no need this for auto increment
        studentData.setStdClass(Integer.parseInt(txtComboClass.getSelectedItem().toString().trim()));
        studentData.setName(txtName.getText().trim());
        studentData.setLastName(txtLastName.getText().trim());
        studentData.setFathersName(txtFatherName.getText().trim());
        studentData.setMothersName(txtMothersName.getText().trim());
        studentData.setAddress(txtAddress.getText().trim());
        studentData.setGender(gender);
        studentData.setDob(DateToSqlDate(txtDate.getDate()));
        studentData.setAge(Integer.parseInt(txtAge.getText().trim()));
        //studentData.setPicturePath(choosePicture.getText());
       
        
        //generateRollNumber();
        
       
        
          
         NewConfirmPayment cp=new NewConfirmPayment(studentData);
         cp.setVisible(true);
         resetNewAdmission();
    }//GEN-LAST:event_btnMakePaymentActionPerformed

    private void btnAdmissionHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdmissionHomeActionPerformed
        // TODO add your handling code here:
        this.dispose();
        sixoptions.setVisible(true);
        resetNewAdmission();
    }//GEN-LAST:event_btnAdmissionHomeActionPerformed

    private void txtMothersNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMothersNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMothersNameActionPerformed

    private void genderFemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderFemaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderFemaleActionPerformed

    private void txtFatherNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFatherNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFatherNameActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLastNameActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        resetNewAdmission();
    }//GEN-LAST:event_btnResetActionPerformed

    private void txtComboClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtComboClassActionPerformed
        // TODO add your handling code here:
        generateRollNumber();
    }//GEN-LAST:event_txtComboClassActionPerformed

    
    
    
    private void generateRollNumber() {
    String query = "SELECT MAX(roll) FROM studentdata WHERE stdClass=?";
    DbCon dbCon = new DbCon();
    PreparedStatement ps;
    Connection connection = null;
    ResultSet rs;

    try {
        int selectedClass = Integer.parseInt(txtComboClass.getSelectedItem().toString());
        ps = dbCon.getCon().prepareStatement(query);
        ps.setInt(1, selectedClass);
        rs = ps.executeQuery();

        while (rs.next()) {
            int maxRoll = rs.getInt("Max(roll)");
            txtRoll.setText(Integer.toString(maxRoll + 1));
        }
    } catch (SQLException ex) {
        Logger.getLogger(NewAdmissionTest.class.getName()).log(Level.SEVERE, null, ex);
    }
}
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewAdmissionTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewAdmissionTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewAdmissionTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewAdmissionTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Sixoptions sixoptions=new Sixoptions();
                NewAdmissionTest newAdmissionTest=new NewAdmissionTest(sixoptions);
                newAdmissionTest.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdmissionHome;
    private javax.swing.JButton btnMakePayment;
    private javax.swing.JButton btnReset;
    private javax.swing.JLabel choosePicture;
    private javax.swing.JRadioButton genderFemale;
    private javax.swing.JRadioButton genderMale;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtAddress;
    private javax.swing.JTextField txtAge;
    private javax.swing.JComboBox<String> txtComboClass;
    private com.toedter.calendar.JDateChooser txtDate;
    private javax.swing.JTextField txtFatherName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtMothersName;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtRoll;
    // End of variables declaration//GEN-END:variables
}
