/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.sql.Connection;
import java.sql.Date;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import model.StudentData;
import util.DbCon;

/**
 *
 * @author imran
 */
public class NewConfirmPayment extends javax.swing.JFrame {

    /**
     * Creates new form NewConfirmPayment
     */
    
    
    Sixoptions sixoptions ;
     NewAdmissionTest show=new NewAdmissionTest(sixoptions);
    private final StudentData studentData;
   
    
    public NewConfirmPayment(StudentData studentData) {
        setUndecorated(true);
        initComponents();
        this.studentData=studentData;
        DbCon databaseConnection=new DbCon();
           Connection Connection=databaseConnection.getCon();
                 
           
           
           this.setLocationRelativeTo(null);
           
           
    }
    
              
          
           
    

    private NewConfirmPayment() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        
    }
    
    
     public Date DateToSqlDate(java.util.Date utilDate){
        if(utilDate !=null){
            return new Date(utilDate.getTime());
        }
        return null;
    }
    
    


public void radioButtonReset() {
    if (radioCashPayment.isSelected()) {
        // If "Cash Payment" is selected, hide components for other payment methods
        txtAccountNumber.setVisible(false);
        txtNameOfTheCard.setVisible(false);
        labelAccountNumber.setVisible(false);
        labelNameoftheCard.setVisible(false);
    }  if(radioBank.isSelected()) {
        // If it's not "Cash Payment," make sure these components are visible.
        txtAccountNumber.setVisible(true);
        txtNameOfTheCard.setVisible(true);
        labelAccountNumber.setVisible(true);
        labelNameoftheCard.setVisible(true);
    }
    
     if(radioBkash.isSelected()) {
        // If it's not "Cash Payment," make sure these components are visible.
        txtAccountNumber.setVisible(true);
        txtNameOfTheCard.setVisible(true);
        labelAccountNumber.setVisible(true);
        labelNameoftheCard.setVisible(true);
    }
     if(radioNogod.isSelected()) {
        // If it's not "Cash Payment," make sure these components are visible.
        txtAccountNumber.setVisible(true);
        txtNameOfTheCard.setVisible(true);
        labelAccountNumber.setVisible(true);
        labelNameoftheCard.setVisible(true);
    }
     if(radioRocket.isSelected()) {
        // If it's not "Cash Payment," make sure these components are visible.
        txtAccountNumber.setVisible(true);
        txtNameOfTheCard.setVisible(true);
        labelAccountNumber.setVisible(true);
        labelNameoftheCard.setVisible(true);
    }
    // Repeat similar visibility checks for other radio buttons if needed.
//    if (radioBkash.isSelected()) {
//        // Hide or show components for Bkash payment
//    }
    // Add similar blocks for other radio buttons (Nogod, Rocket, Bank).
}
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnMakePaymentBack = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        radioNogod = new javax.swing.JRadioButton();
        radioBkash = new javax.swing.JRadioButton();
        radioBank = new javax.swing.JRadioButton();
        radioRocket = new javax.swing.JRadioButton();
        radioCashPayment = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        labelAccountNumber = new javax.swing.JLabel();
        txtAccountNumber = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtPaymentDate = new com.toedter.calendar.JDateChooser();
        jLabel12 = new javax.swing.JLabel();
        txtAmount = new javax.swing.JTextField();
        labelNameoftheCard = new javax.swing.JLabel();
        txtNameOfTheCard = new javax.swing.JTextField();
        btnConfirmPayment = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel3.setText("Online or Cash Payment ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 250, 30));

        btnMakePaymentBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/previous.png"))); // NOI18N
        btnMakePaymentBack.setText("Back");
        btnMakePaymentBack.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnMakePaymentBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMakePaymentBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnMakePaymentBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 20, 90, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 60));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel1.setText("Make Payment");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 220, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Select Payment Options");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 190, 20));

        buttonGroup1.add(radioNogod);
        radioNogod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioNogodActionPerformed(evt);
            }
        });
        jPanel2.add(radioNogod, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 20, 20));

        buttonGroup1.add(radioBkash);
        radioBkash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBkashActionPerformed(evt);
            }
        });
        jPanel2.add(radioBkash, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 20, -1));

        buttonGroup1.add(radioBank);
        radioBank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBankActionPerformed(evt);
            }
        });
        jPanel2.add(radioBank, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 150, -1, -1));

        buttonGroup1.add(radioRocket);
        radioRocket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioRocketActionPerformed(evt);
            }
        });
        jPanel2.add(radioRocket, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 150, -1, -1));

        buttonGroup1.add(radioCashPayment);
        radioCashPayment.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        radioCashPayment.setText("Cash Payment");
        radioCashPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioCashPaymentActionPerformed(evt);
            }
        });
        jPanel2.add(radioCashPayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/payment/banktransfer1.png"))); // NOI18N
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 130, 120, 50));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/payment/bkash (1).png"))); // NOI18N
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 130, 70));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/payment/nogod (2).png"))); // NOI18N
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 130, 50));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/payment/rockettest.png"))); // NOI18N
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 130, 120, 60));

        labelAccountNumber.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelAccountNumber.setText("Account Number:");
        jPanel2.add(labelAccountNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 287, 130, 30));
        jPanel2.add(txtAccountNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 290, 180, 30));

        jLabel11.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel11.setText("Payment Date");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 400, -1, -1));
        jPanel2.add(txtPaymentDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 390, 180, 30));

        jLabel12.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel12.setText("Amount");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, 60, -1));
        jPanel2.add(txtAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 340, 180, 30));

        labelNameoftheCard.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelNameoftheCard.setText("Name On the Card");
        jPanel2.add(labelNameoftheCard, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 450, -1, -1));

        txtNameOfTheCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameOfTheCardActionPerformed(evt);
            }
        });
        jPanel2.add(txtNameOfTheCard, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 440, 180, 30));

        btnConfirmPayment.setBackground(new java.awt.Color(0, 153, 0));
        btnConfirmPayment.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnConfirmPayment.setForeground(new java.awt.Color(255, 255, 255));
        btnConfirmPayment.setText("Confirm Payment");
        btnConfirmPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmPaymentActionPerformed(evt);
            }
        });
        jPanel2.add(btnConfirmPayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 530, 390, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 830, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmPaymentActionPerformed
        // TODO add your handling code here:
        String payment="";
        if(radioBkash.isSelected()){
            payment="Bkash";
        }
        else if(radioNogod.isSelected()){
            payment="Nogod";
        }
        else if(radioRocket.isSelected()){
            payment="Rocket";
        }
        else if(radioBank.isSelected()){
            payment="Bank";
        }
        else{
            payment="Not pay";
        }
        
        
        
        String accountNumber=txtAccountNumber.getText();
        Date paymentDate=DateToSqlDate(txtPaymentDate.getDate());
        Double amount=Double.parseDouble(txtAmount.getText());
        String nameOnCard=txtNameOfTheCard.getText();
        String paymentMethod=payment;
        
        
        
        studentData.setAccountNumber(accountNumber);
        studentData.setAmount(amount);
        studentData.setPaymentDate(paymentDate);
        studentData.setCardName(nameOnCard);
        studentData.setPaymentMethod(paymentMethod);
        
        
        
        DbCon databaseConnection=new DbCon();
        databaseConnection.saveStudentDataToDatabase(studentData);
        
        
        
       
        
        
                
        
        
        JOptionPane.showMessageDialog(this, "payment Confirmed ","Confirmation",JOptionPane.INFORMATION_MESSAGE);
        show.resetNewAdmission();//   method gula dhorthe partica but txtfield gula pacce na  Ctrl + click to check
        this.dispose();
        
    }//GEN-LAST:event_btnConfirmPaymentActionPerformed

    
    private void btnMakePaymentBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMakePaymentBackActionPerformed
        // TODO add your handling code here:
        
        this.dispose();
        
        
    }//GEN-LAST:event_btnMakePaymentBackActionPerformed

    private void txtNameOfTheCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameOfTheCardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameOfTheCardActionPerformed

    private void radioCashPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioCashPaymentActionPerformed
        // TODO add your handling code here:
        radioButtonReset();
    }//GEN-LAST:event_radioCashPaymentActionPerformed

    private void radioBkashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBkashActionPerformed
        // TODO add your handling code here:
        radioButtonReset();
    }//GEN-LAST:event_radioBkashActionPerformed

    private void radioNogodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioNogodActionPerformed
        // TODO add your handling code here:
        radioButtonReset();
    }//GEN-LAST:event_radioNogodActionPerformed

    private void radioRocketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioRocketActionPerformed
        // TODO add your handling code here:
        radioButtonReset();
    }//GEN-LAST:event_radioRocketActionPerformed

    private void radioBankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBankActionPerformed
        // TODO add your handling code here:
        radioButtonReset();
    }//GEN-LAST:event_radioBankActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewConfirmPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewConfirmPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewConfirmPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewConfirmPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
             
                new NewConfirmPayment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmPayment;
    private javax.swing.JButton btnMakePaymentBack;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelAccountNumber;
    private javax.swing.JLabel labelNameoftheCard;
    private javax.swing.JRadioButton radioBank;
    private javax.swing.JRadioButton radioBkash;
    private javax.swing.JRadioButton radioCashPayment;
    private javax.swing.JRadioButton radioNogod;
    private javax.swing.JRadioButton radioRocket;
    private javax.swing.JTextField txtAccountNumber;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JTextField txtNameOfTheCard;
    private com.toedter.calendar.JDateChooser txtPaymentDate;
    // End of variables declaration//GEN-END:variables
}
