/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.Image;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import model.StudentData;
import util.DbCon;

/**
 *
 * @author imran
 */
public class Profiles extends javax.swing.JFrame {

    
    
/**
     * Creates new form Profiles
     */
    //for back
    
    private Sixoptions sixoptions;
        public Profiles(Sixoptions sixoptions) {
            setUndecorated(true);
        initComponents();
        setLocationRelativeTo(null);
        this.sixoptions=sixoptions;
          
        
    }
    
    
     
    
    
    public StudentData retrieveStudentData(int roll, int stdClass){
        StudentData studentData1=null;
        
        DbCon databaseConnection=new DbCon();
        Connection con=databaseConnection.getCon();
        
        if(con !=null){
            
            try {
                String query="select * from studentdata where roll=? and stdClass=?";
                PreparedStatement pstmt=con.prepareStatement(query);
                
                pstmt.setInt(1, roll);
                pstmt.setInt(2, stdClass);
                ResultSet rs=pstmt.executeQuery();
                
                if(rs.next()){
                    String name=rs.getString("name");
                    String gender=rs.getString("gender");
                    String address=rs.getString("address");
                    Date dob=rs.getDate("dob");
                    int age=rs.getInt("age");
                    String picturePath=rs.getString("picturePath");
                    
                    //studentData1 =new StudentData(traineeId, batchId, name, gender, address, dob, age, gender, dob, batchId, name, picturePath);
                    studentData1=new StudentData(roll, stdClass, name, name, name, name, address, gender, dob, age, picturePath, gender, ABORT, dob, name, picturePath);
                }
                
            } catch (SQLException ex) {
                Logger.getLogger(Profiles.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
        
        return studentData1;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtRoll = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtClass = new javax.swing.JTextField();
        btnShow = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        profilePic = new javax.swing.JLabel();
        profileName = new javax.swing.JLabel();
        profileAddress = new javax.swing.JLabel();
        profileTraineeId = new javax.swing.JLabel();
        profileBatchId = new javax.swing.JLabel();
        profileGender = new javax.swing.JLabel();
        profileDob = new javax.swing.JLabel();
        profileAge = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(60, 92, 72));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Profile DashBoard");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 870, 60));

        btnBack.setBackground(new java.awt.Color(204, 255, 204));
        btnBack.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/left.png"))); // NOI18N
        btnBack.setText("Back");
        btnBack.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 110, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 60));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel2.setText("Roll");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 80, 30));

        txtRoll.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(txtRoll, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 150, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel3.setText("Class");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, -1, 30));

        txtClass.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(txtClass, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 30, 190, 30));

        btnShow.setBackground(new java.awt.Color(51, 153, 0));
        btnShow.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnShow.setForeground(new java.awt.Color(255, 255, 255));
        btnShow.setText("Show");
        btnShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowActionPerformed(evt);
            }
        });
        jPanel2.add(btnShow, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 20, 120, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1010, 80));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        profilePic.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        profilePic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel3.add(profilePic, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 150, 140));

        profileName.setFont(new java.awt.Font("SansSerif", 1, 22)); // NOI18N
        jPanel3.add(profileName, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 200, 50));

        profileAddress.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jPanel3.add(profileAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 220, 50));

        profileTraineeId.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jPanel3.add(profileTraineeId, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, 160, 40));

        profileBatchId.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jPanel3.add(profileBatchId, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, 100, 30));

        profileGender.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jPanel3.add(profileGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 150, 110, 30));

        profileDob.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jPanel3.add(profileDob, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 230, 120, 30));

        profileAge.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jPanel3.add(profileAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 310, 70, 30));

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Information");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 160, 40));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 1010, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents
 
    private void btnShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowActionPerformed
        // TODO add your handling code here:
        
        if(txtRoll.getText().isEmpty() || txtClass.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Field cannot Be Empty");
            return;
        }
       
        
        
        int roll=Integer.parseInt(txtRoll.getText().trim());
        int stdClass=Integer.parseInt(txtClass.getText().trim());
        
        
        StudentData studentData=retrieveStudentData(roll, stdClass);
        
        if(studentData !=null){
            
            profileName.setText("Name : "+studentData.getName());
            profileAddress.setText("Address: "+ studentData.getAddress());
            profileGender.setText("Gender: "+studentData.getGender());
            profileDob.setText("DOB: "+studentData.getDob().toString());
            profileAge.setText("Age: "+studentData.getAge());
            profileTraineeId.setText("Roll : "+studentData.getRoll());
            profileBatchId.setText("Class : "+studentData.getStdClass());
            
            
            ImageIcon imageIcon=new ImageIcon(studentData.getPicturePath());
            Image image=imageIcon.getImage().getScaledInstance(profilePic.getWidth(), profilePic.getHeight(), Image.SCALE_SMOOTH);
            profilePic.setIcon(new ImageIcon(image));
        }
        else{
            JOptionPane.showMessageDialog(this, "No student found for given Trainee Id and Batch Id");
            
        }
    }//GEN-LAST:event_btnShowActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        profileName.setText("");
        profileAddress.setText("");
        profileGender.setText("");
        profileDob.setText("");
        profileAge.setText("");
        profileTraineeId.setText("");
        profileBatchId.setText("");
        
        txtRoll.setText("");
        txtClass.setText("");
        profilePic.setIcon(null);
        
        
        sixoptions.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Profiles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Profiles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Profiles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Profiles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Sixoptions sixoptions=new Sixoptions();
                Profiles profiles=new Profiles(sixoptions);
                profiles.setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnShow;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel profileAddress;
    private javax.swing.JLabel profileAge;
    private javax.swing.JLabel profileBatchId;
    private javax.swing.JLabel profileDob;
    private javax.swing.JLabel profileGender;
    private javax.swing.JLabel profileName;
    private javax.swing.JLabel profilePic;
    private javax.swing.JLabel profileTraineeId;
    private javax.swing.JTextField txtClass;
    private javax.swing.JTextField txtRoll;
    // End of variables declaration//GEN-END:variables
}
